### ISSUE TITLE
ビーチボールの節面を簡単に描画する方法

### ISSUE THREAD

**Issue by msomeya1** [tktmyd/pygmt-howto-jp#1]
（しょぼくて恐縮ですが、こういうのは小さくてもどんどんフィードバックを送るべきと思いまして…）

https://tktmyd.github.io/pygmt-howto-jp/mech.html
の下の方に
```
fig.meca(spec  = meca, 
         scale = '1c', 
         cmap  = True, 
)
# 節面を描画するにはもういちど fig.meca を `nodal` オプションをつけて呼ぶ
fig.meca(
    spec  = meca, 
    scale = '1c', 
    pen   = 'default,black', 
    nodal = '0'
)
```
とありますが、節面を描画する`outline`オプションがあるようです。
すなわち
```
fig.meca(
         spec  = meca, 
         scale = '1c', 
         cmap  = True, 
         outline=True
)
```
だけで機能します。

参考：
https://www.pygmt.org/dev/api/generated/pygmt.Figure.meca.html#:~:text=circumference%20of%20beachball.-,outline,-(bool%20or

染矢

**Comment by tktmyd** [comment]
染谷さん

**Comment by tktmyd** [comment]
染矢さん @msomeya1 ご指摘ありがとうございます．
たしかにご指摘のコードで簡単に描画できますね．調べてみたところ，2023年9月のリリース `v0.10.0` で `outline` オプションが実装されたようでした（参考：[Changelog](https://www.pygmt.org/dev/changes.html#release-v0-10-0-2023-09-02), [該当Issue](https://github.com/GenericMappingTools/pygmt/pull/2546)）．もともとのHowtoの記事を執筆したのが2023年6月で，その後更新しておらず，新オプションの実装にも気づいていませんでした．

私自身いつも不便に思いながら使っていたので，ご指摘大変助かりました．さっそく該当ページも更新しました（謝辞としてお名前を挙げさせていただきましたが，よかったでしょうか？）．
これからもこういった気付きがありましたら，どんどんIssueでお知らせください．

**Comment by msomeya1** [comment]
前田先生

早速のupdateありがとうございます。
名前の使用も全く問題ありません。

また何か気づいたらisssueを送りたいと思いますので、これからもよろしくお願いします。

**Comment by tktmyd** [comment]
Issue #2 の修正に関連して，漢字名が間違っている（谷→矢）ことに気が付きました…大変申し訳無いです．Web上の謝辞も修正いたしました．
